remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Food.com Recipe Analytics
description: EECS398 Project that tried to predict a recipe's rating based on its complexity
show_downloads: false
